import { Header } from '@/Components/Header';
import type { Metadata } from 'next';
import './globals.css';
import { GlobalProvider } from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className='relative h-screen w-full bg-stone-950 text-white no-underline'>
        <GlobalProvider>
          <Header />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
